version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: budgeteer
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      db_net:
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@db.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8081:80"
    networks:
      db_net:

volumes:
  db:

networks:
  db_net: