services:
  db:
    image: postgres:18.4-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: budgeteer
    volumes:
      - db:/var/lib/postgresql
      - ./scripts/docker/initdb/:/docker-entrypoint-initdb.d
    networks:
      db_net:
    ports:
      - "5432:5432"
  metabase:
    image: metabase/metabase:latest
    restart: on-failure
    ports:
      - "3000:3000"
    networks:
      db_net:
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: meta_db
      MB_DB_PORT: 5432
      MB_DB_USER: admin
      MB_DB_PASS: password
      MB_DB_HOST: db


volumes:
  db:
  app_data:

networks:
  db_net: