spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.jpa.hibernate.ddl-auto=validate

server.error.whitelabel.enabled=false
spring.mvc.throw-exception-if-no-handler-found=true

spring.output.ansi.enabled=always
