CREATE TABLE categories (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR NOT NULL,
    parent_id INTEGER REFERENCES categories (id) ON DELETE RESTRICT
);

CREATE TABLE items (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR NOT NULL,
    default_cost NUMERIC(12,2),
    category_id INTEGER REFERENCES categories (id) ON DELETE RESTRICT
);

CREATE TABLE expenses(
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    item_id INTEGER REFERENCES items (id) ON DELETE RESTRICT,
    cost NUMERIC(12,2) NOT NULL,
    amount INTEGER,
    bought_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE income_types(
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR NOT NULL,
    parent_id INTEGER REFERENCES income_types (id) ON DELETE RESTRICT
);

CREATE TABLE incomes(
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    amount NUMERIC(12,2) NOT NULL,
    type_id INTEGER REFERENCES income_types(id) ON DELETE RESTRICT,
    notes VARCHAR,
    received_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);
